[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npx prisma generate", "npx nest build"]

[start]
cmd = "npx prisma migrate deploy && node dist/main"
